### ISSUE TITLE
Test pre-trained model on my own image without label

### ISSUE THREAD

**Issue by gruossomonica** [kampelmuehler/synthesizing_human_like_sketches#1]
Hi. Your work is interesting! I would like to try it. Can your pre-trained model be used to test on my images without labels?

**Comment by kampelmuehler** [comment]
Hi,
I'm afraid that the full pre-trained model requires label input for it to work and thus labels are required in any case. You would have to use a model without the AdaIn part.
Moritz

**Comment by gruossomonica** [comment]
Ok. Thank you for the quick replay. I just checked the test file and saw that there is a "tree" label, which interests me. I'll try then.
Thanks again!
