### ISSUE TITLE
Inverted output?

### ISSUE THREAD

**Issue by naoto0804** [kampelmuehler/synthesizing_human_like_sketches#2]
Thank you for releasing the code!
When I tested the code, the result is like below (the background is painted in black and the strokes are painted in white).
However, for all the figures in your paper the background is painted in white.
Did you manually invert the result images? Or, do I miss something important facts?

```
python test.py --img_path test_images/fish.png --label fish
```

![fish_processed](https://user-images.githubusercontent.com/7067992/95572267-ab302a80-0a64-11eb-8e1b-24975aecd97e.png)

**Comment by kampelmuehler** [comment]
Yes, you are correct. I inverted the figures because it is better for visibility and in print, however for the network the background is assumed to be all 0 arbitrarily.

**Comment by naoto0804** [comment]
That makes sense, thanks!

**Comment by naoto0804** [comment]
Let me ask one more.
The result is indeed promising but the generated images have a lot of artifacts; 
Have you tried some kind of patch-wise adversarial loss like the one used in CycleGAN? Didn't it work?

**Comment by kampelmuehler** [comment]
You are right. 
The artifacts are to a large part due to the upsamling in the decoder. A patch-wise adversarial loss would certainly also improve the visual appeal. While I have tried it, it's out of the scope of this work.

**Comment by naoto0804** [comment]
I see, thanks!
